export const menuItems = [
  {
    title: 'Ranking',
    url: '/ranking',
    cName: 'nav-links',
  },
  {
    title: 'Contacto',
    url: '/contacto',
    cName: 'nav-links',
  },
];

export const playersRanking = {
  '6° Caballeros': [
    {
      name: 'Miranda Paolo',
      score: [100, 0, 0, 0, 0],
      total: 100,
    },
    {
      name: 'Campos Alejandro',
      score: [100, 0, 0, 0, 0],
      total: 100,
    },
    {
      name: 'Carrizo Daniel',
      score: [80, 0, 0, 0, 0],
      total: 80,
    },
    {
      name: 'Garcia Maximiliano',
      score: [80, 0, 0, 0, 0],
      total: 80,
    },
    {
      name: 'Wollert Michel',
      score: [60, 0, 0, 0, 0],
      total: 60,
    },
    {
      name: 'Chaparro Yamil',
      score: [60, 0, 0, 0, 0],
      total: 60,
    },
    {
      name: 'Huber Walter',
      score: [60, 0, 0, 0, 0],
      total: 60,
    },
    {
      name: 'Sanchez Joaquín',
      score: [60, 0, 0, 0, 0],
      total: 60,
    },
    {
      name: 'Feit Hugo',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Leiva Sandro',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Borgert Nicolas',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Mayer Cristian',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Cortina Sandro',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Cardenal Valentin',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Jung Fabian',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Kern Jonatan',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Taulada Valentin',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Rodriguez Nicolas',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Ibarra Jose',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Bill Juan Ignacio',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Segurado Ramiro',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Madrid Alejandro',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Schmidt Martin',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Schmidt Emanuel',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Cuccuza Javier',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Santa Maria',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Genovesio Lucas',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Diaz Silvestre',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Escudero Nicolas',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Mingiaca Facundo',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Iriarte Gaston',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Farias Gaston',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Neif Facundo',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Fuchs Damian',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
  ],
  '7° Damas': [
    {
      name: 'Aguilar Vanesa',
      score: [100, 0, 0, 0, 0],
      total: 100,
    },
    {
      name: 'Marquez Dariana',
      score: [100, 0, 0, 0, 0],
      total: 100,
    },
    {
      name: 'Sigvard Julia',
      score: [80, 0, 0, 0, 0],
      total: 80,
    },
    {
      name: 'Miño Natalia',
      score: [80, 0, 0, 0, 0],
      total: 80,
    },
    {
      name: 'Herman Nancy',
      score: [60, 0, 0, 0, 0],
      total: 60,
    },
    {
      name: 'Pfeiffer Debora',
      score: [60, 0, 0, 0, 0],
      total: 60,
    },
    {
      name: 'Aguilar Eugenia',
      score: [60, 0, 0, 0, 0],
      total: 60,
    },
    {
      name: 'Fischer Romina',
      score: [60, 0, 0, 0, 0],
      total: 60,
    },
    {
      name: 'Darrechon Daniela',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Reh Eleonora',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Battisti Hilen',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Battisti Zoe',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Seiffert Florencia',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Fontana Maria',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Graf Angelina',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Pavon Norma',
      score: [40, 0, 0, 0, 0],
      total: 40,
    },
    {
      name: 'Chaparro Lorena',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Muller Lorena',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Bentancor Irene',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Morales Cristina',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Jumilla Yohana',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Erbes Selene',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Muñoz Eugenia',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Gardella Monica',
      score: [25, 0, 0, 0, 0],
      total: 25,
    },
    {
      name: 'Castañeda Claudia',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Parra Sonia',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Heffel Mariela',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Alvarez Agustina',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Schlotauer Ari',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Herman Cintia',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Garcia Luisina',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Ocampos Antonela',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Markel Antonela',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Olmedo Paula',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Heffele Carla',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
    {
      name: 'Heffele Pamela',
      score: [10, 0, 0, 0, 0],
      total: 10,
    },
  ],
  // 'Suma 10': [
  //   {
  //     name: 'Cavagna Ignacio',
  //     score: [10, 100, 80, 40, 80],
  //     total: 310,
  //     category: '4°',
  //   },
  //   {
  //     name: 'Momparler Tomas',
  //     score: [60, 80, 60, 80, 10],
  //     total: 290,
  //     category: '4°',
  //   },
  //   {
  //     name: 'Martinez Carlos',
  //     score: [100, 40, 40, 100, 10],
  //     total: 290,
  //     category: '4°',
  //   },
  //   {
  //     name: 'Randazzo Mateo',
  //     score: [0, 0, 80, 100, 100],
  //     total: 280,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Peralta Leandro',
  //     score: [10, 60, 40, 60, 100],
  //     total: 270,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Martinez Juan Jose',
  //     score: [40, 40, 60, 60, 40],
  //     total: 240,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Wollert Michel',
  //     score: [0, 40, 60, 60, 40],
  //     total: 200,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Levy Marcos',
  //     score: [100, 10, 60, 10, 0],
  //     total: 180,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Fernandez Manuel',
  //     score: [10, 60, 40, 10, 60],
  //     total: 180,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Schmidt Franco',
  //     score: [10, 40, 100, 10, 10],
  //     total: 170,
  //     category: '3°',
  //   },
  //   {
  //     name: 'Wagner Ignacio',
  //     score: [0, 80, 0, 80, 0],
  //     total: 160,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Tiraboschi Nicolas',
  //     score: [10, 100, 0, 0, 40],
  //     total: 150,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Azcarate Jose',
  //     score: [10, 40, 0, 60, 40],
  //     total: 150,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Knoll Gonzalo',
  //     score: [40, 40, 0, 40, 0],
  //     total: 120,
  //     category: '4°',
  //   },
  //   {
  //     name: 'Lopez Cristian',
  //     score: [40, 40, 0, 40, 0],
  //     total: 120,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Sinner Juan',
  //     score: [0, 60, 0, 0, 60],
  //     total: 120,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Muller Alan',
  //     score: [60, 10, 0, 40, 0],
  //     total: 110,
  //     category: '6° OBS',
  //   },
  //   {
  //     name: 'Acosta Axel',
  //     score: [40, 60, 10, 0, 0],
  //     total: 110,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Schmidt Martin',
  //     score: [0, 0, 100, 0, 0],
  //     total: 100,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Schonals Gustavo',
  //     score: [0, 10, 0, 25, 60],
  //     total: 95,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Zapata Lautaro',
  //     score: [0, 10, 40, 40, 0],
  //     total: 90,
  //     category: '4°',
  //   },
  //   {
  //     name: 'Gonzalez Gerardo',
  //     score: [80, 0, 0, 10, 0],
  //     total: 90,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Massera Cristian',
  //     score: [0, 0, 0, 25, 60],
  //     total: 85,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Vaccareti Gonzalo',
  //     score: [0, 0, 0, 0, 80],
  //     total: 80,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Franco Juan Manuel',
  //     score: [80, 0, 0, 0, 0],
  //     total: 80,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Neif Facundo',
  //     score: [0, 25, 40, 0, 0],
  //     total: 65,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Quinodoz Franco',
  //     score: [60, 0, 0, 0, 0],
  //     total: 60,
  //     category: '4°',
  //   },
  //   {
  //     name: 'Cardoso Julian',
  //     score: [60, 0, 0, 0, 0],
  //     total: 60,
  //     category: '6° OBS',
  //   },
  //   {
  //     name: 'Eichman Gonzalo',
  //     score: [10, 10, 40, 0, 0],
  //     total: 60,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Saralegui Eliseo',
  //     score: [0, 10, 40, 10, 0],
  //     total: 60,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Fuchs Damian',
  //     score: [0, 10, 40, 10, 0],
  //     total: 60,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Escudero Nicolas',
  //     score: [0, 0, 0, 40, 0],
  //     total: 40,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Gomez Nicolas',
  //     score: [0, 0, 0, 40, 0],
  //     total: 40,
  //     category: '3°',
  //   },
  //   {
  //     name: 'Gareis Maximiliano',
  //     score: [0, 0, 0, 40, 0],
  //     total: 40,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Molina Pablo',
  //     score: [40, 0, 0, 0, 0],
  //     total: 40,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Romero Emanuel',
  //     score: [40, 0, 0, 0, 0],
  //     total: 40,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Quinteros Lucas',
  //     score: [40, 0, 0, 0, 0],
  //     total: 40,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Huber Juan',
  //     score: [40, 0, 0, 0, 0],
  //     total: 40,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Schmidt Emanuel',
  //     score: [0, 40, 0, 0, 0],
  //     total: 40,
  //     category: '7 OBS°',
  //   },
  //   {
  //     name: 'Drasdov Gonzalo',
  //     score: [0, 25, 0, 0, 0],
  //     total: 25,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Schmidt Gustavo',
  //     score: [10, 0, 0, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Gadea Facundo',
  //     score: [0, 10, 0, 0, 0],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Stieben Lothar',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Lopez Emiliano',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '4°',
  //   },
  //   {
  //     name: 'Martinez Amilcar',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Ross Maximiliano',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Kliphan Mauricio',
  //     score: [0, 0, 0, 10, 0],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Clementin Nestor',
  //     score: [0, 0, 0, 10, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Cardenal Valentin',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Feit Hugo',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '6°',
  //   },
  // ],
  // 'Suma 12': [
  //   {
  //     name: 'Peralta Leandro',
  //     score: [25, 100, 100, 40, 40],
  //     total: 305,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Levy Marcos',
  //     score: [25, 80, 40, 100, 60],
  //     total: 305,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Randazzo Mateo',
  //     score: [60, 80, 40, 100, 0],
  //     total: 280,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Kramer Bruno',
  //     score: [100, 40, 60, 25, 25],
  //     total: 250,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Molina Pablo',
  //     score: [80, 40, 25, 40, 60],
  //     total: 245,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Gaitan Joaquin',
  //     score: [0, 10, 80, 60, 80],
  //     total: 230,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Borgert Nicolas',
  //     score: [25, 100, 10, 25, 60],
  //     total: 220,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Campos Alejandro',
  //     score: [80, 40, 10, 0, 80],
  //     total: 210,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Eichman Gonzalo',
  //     score: [100, 40, 60, 0, 0],
  //     total: 200,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Escudero Nicolas',
  //     score: [40, 10, 80, 60, 0],
  //     total: 190,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Chaparro Yamil',
  //     score: [0, 10, 100, 40, 40],
  //     total: 190,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Segurado Ramiro',
  //     score: [25, 40, 40, 40, 10],
  //     total: 155,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Rios Tati',
  //     score: [60, 25, 60, 0, 0],
  //     total: 145,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Wollert Michel',
  //     score: [25, 40, 25, 25, 25],
  //     total: 140,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Muller Alan',
  //     score: [25, 25, 25, 60, 0],
  //     total: 135,
  //     category: '6° OBS',
  //   },
  //   {
  //     name: 'Miranda Paolo',
  //     score: [0, 40, 40, 25, 25],
  //     total: 130,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Jung Fabian',
  //     score: [0, 25, 0, 80, 25],
  //     total: 130,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Paredes Miguel',
  //     score: [0, 25, 0, 80, 25],
  //     total: 130,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Martinez Juan Jose',
  //     score: [40, 25, 25, 0, 40],
  //     total: 130,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Neif Facundo',
  //     score: [40, 25, 0, 25, 40],
  //     total: 130,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Mayer Cristian',
  //     score: [40, 10, 25, 40, 10],
  //     total: 125,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Cortina Sandro',
  //     score: [0, 0, 25, 40, 60],
  //     total: 125,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Phfarer Martin',
  //     score: [0, 0, 0, 25, 100],
  //     total: 125,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Azcarate Jose',
  //     score: [60, 25, 0, 10, 25],
  //     total: 120,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Fernandez Manuel',
  //     score: [10, 10, 60, 25, 10],
  //     total: 115,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Fuchs Damian',
  //     score: [25, 25, 25, 0, 40],
  //     total: 115,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Cardenal Valentin',
  //     score: [10, 10, 25, 60, 10],
  //     total: 115,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Mingiaca Facundo',
  //     score: [25, 25, 25, 10, 25],
  //     total: 110,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Gadea Facundo',
  //     score: [0, 0, 0, 0, 100],
  //     total: 100,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Huber Walter',
  //     score: [0, 25, 10, 40, 25],
  //     total: 100,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Feit Hugo',
  //     score: [40, 0, 10, 0, 40],
  //     total: 90,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Massera Cristian',
  //     score: [10, 25, 10, 25, 0],
  //     total: 70,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Schmidt Martin',
  //     score: [0, 0, 25, 10, 25],
  //     total: 60,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Ulrich Lautaro',
  //     score: [0, 60, 0, 0, 0],
  //     total: 60,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Gimenez Tomas',
  //     score: [0, 60, 0, 0, 0],
  //     total: 60,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Rosales Angelo',
  //     score: [60, 0, 0, 0, 0],
  //     total: 60,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Tiraboschi Nicolas',
  //     score: [0, 60, 0, 0, 0],
  //     total: 60,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Martinez Joel',
  //     score: [0, 60, 0, 0, 0],
  //     total: 60,
  //     category: '7° OBS',
  //   },
  //   {
  //     name: 'Goette German',
  //     score: [40, 10, 10, 0, 0],
  //     total: 60,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Cuti Omar',
  //     score: [40, 10, 10, 0, 0],
  //     total: 60,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Percara Renzo',
  //     score: [0, 10, 40, 10, 0],
  //     total: 60,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Madrid Alejandro',
  //     score: [10, 10, 10, 10, 10],
  //     total: 50,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Crettaz Jonas',
  //     score: [0, 10, 40, 0, 0],
  //     total: 50,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Ruff Ariel',
  //     score: [0, 40, 0, 10, 0],
  //     total: 50,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Frank Alan',
  //     score: [0, 0, 25, 10, 10],
  //     total: 45,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Martinez Rene',
  //     score: [40, 0, 0, 0, 0],
  //     total: 40,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Leones Thomas',
  //     score: [0, 0, 40, 0, 0],
  //     total: 40,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Schimpf Mateo',
  //     score: [0, 0, 40, 0, 0],
  //     total: 40,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Wagner Ignacio',
  //     score: [0, 0, 0, 0, 40],
  //     total: 40,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Schonals Gustavo',
  //     score: [0, 0, 0, 40, 0],
  //     total: 40,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Schmidt Emanuel',
  //     score: [0, 0, 0, 10, 25],
  //     total: 35,
  //     category: '7° OBS',
  //   },
  //   {
  //     name: 'Genovesio Lucas',
  //     score: [0, 0, 0, 10, 25],
  //     total: 35,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Gentina Matias',
  //     score: [25, 10, 0, 0, 0],
  //     total: 35,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Benitez Rodrigo',
  //     score: [10, 0, 0, 10, 10],
  //     total: 30,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Ceschi Alan',
  //     score: [25, 0, 0, 0, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Cavagna Ignacio',
  //     score: [25, 0, 0, 0, 0],
  //     total: 25,
  //     category: '4°',
  //   },
  //   {
  //     name: 'Cavagna Gustavo',
  //     score: [25, 0, 0, 0, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Diaz Silvestre',
  //     score: [0, 0, 25, 0, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Fuchs Hernan',
  //     score: [0, 0, 0, 25, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Acosta Axel',
  //     score: [0, 0, 0, 0, 25],
  //     total: 25,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Muller Juanchi',
  //     score: [0, 0, 0, 25, 0],
  //     total: 25,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Todoni Brian',
  //     score: [0, 0, 0, 25, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Brauer Ariel',
  //     score: [10, 0, 10, 0, 0],
  //     total: 20,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Heffel Joel',
  //     score: [10, 0, 10, 0, 0],
  //     total: 20,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Alvarez Josefina',
  //     score: [10, 0, 0, 0, 0],
  //     total: 10,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Antivero Luciano',
  //     score: [10, 0, 0, 0, 0],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Bill Gaston',
  //     score: [10, 0, 0, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Montenegro Cris',
  //     score: [10, 0, 0, 0, 0],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Alem Alejandro',
  //     score: [10, 0, 0, 0, 0],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Cavagna Belen',
  //     score: [0, 10, 0, 0, 0],
  //     total: 10,
  //   },
  //   {
  //     name: 'Ingaramo Sebastian',
  //     score: [0, 10, 0, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Gadea Lucas',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Veron Juan',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Retamar Andres',
  //     score: [0, 0, 0, 10, 0],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Bigliani Sebastian',
  //     score: [0, 0, 0, 10, 0],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Carrizo Daniel',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Saralegui Matias',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Ross Maximiliano',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Burgos Ariel',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '7°',
  //   },

  //   // Añade más jugadores de la 'Categoria 2' según sea necesario
  // ],
  // 'Suma 13': [
  //   {
  //     name: 'Esquivel Monica',
  //     score: [40, 60, 100, 80, 60],
  //     total: 340,
  //   },
  //   {
  //     name: 'Albornoz Daniela',
  //     score: [40, 60, 40, 100, 100],
  //     total: 340,
  //   },
  //   {
  //     name: 'Randazzo Carla',
  //     score: [100, 80, 40, 40, 60],
  //     total: 320,
  //   },
  //   {
  //     name: 'Aguilar Eugenia',
  //     score: [40, 40, 80, 60, 80],
  //     total: 300,
  //   },
  //   {
  //     name: 'Kramer Karen',
  //     score: [40, 40, 10, 100, 100],
  //     total: 290,
  //   },
  //   {
  //     name: 'Heffele Clarisa',
  //     score: [0, 60, 100, 80, 40],
  //     total: 280,
  //   },
  //   {
  //     name: 'Mingiaca Mercedes',
  //     score: [60, 40, 80, 60, 25],
  //     total: 265,
  //   },
  //   {
  //     name: 'Barquin Barbara',
  //     score: [100, 0, 25, 40, 40],
  //     total: 205,
  //   },
  //   {
  //     name: 'Acendon Laura',
  //     score: [0, 60, 60, 25, 40],
  //     total: 185,
  //   },
  //   {
  //     name: 'Benencio Gabriela',
  //     score: [60, 0, 60, 25, 40],
  //     total: 185,
  //   },
  //   {
  //     name: 'Cabello Yanina',
  //     score: [0, 40, 40, 25, 80],
  //     total: 185,
  //   },
  //   {
  //     name: 'Morales Cristina',
  //     score: [60, 25, 25, 40, 25],
  //     total: 175,
  //   },
  //   {
  //     name: 'Escudero Dina',
  //     score: [40, 40, 10, 25, 40],
  //     total: 155,
  //   },
  //   {
  //     name: 'Mayer Betiana',
  //     score: [0, 80, 10, 60, 0],
  //     total: 150,
  //   },
  //   {
  //     name: 'Aguilar Vanesa',
  //     score: [25, 40, 40, 0, 40],
  //     total: 145,
  //   },
  //   {
  //     name: 'Marinelli Lujan',
  //     score: [25, 25, 25, 40, 25],
  //     total: 135,
  //   },
  //   {
  //     name: 'Clementin Favia',
  //     score: [0, 100, 0, 25, 10],
  //     total: 135,
  //   },
  //   {
  //     name: 'Miño Natalia',
  //     score: [60, 10, 10, 10, 40],
  //     total: 130,
  //   },
  //   {
  //     name: 'Fischer Romina',
  //     score: [40, 25, 25, 25, 0],
  //     total: 115,
  //   },
  //   {
  //     name: 'Azcarate Magali',
  //     score: [25, 40, 10, 10, 25],
  //     total: 110,
  //   },
  //   {
  //     name: 'Muller Melanie',
  //     score: [0, 100, 0, 0, 10],
  //     total: 110,
  //   },
  //   {
  //     name: 'Alberto Mariana',
  //     score: [40, 0, 60, 0, 0],
  //     total: 100,
  //   },
  //   {
  //     name: 'Sigvardt Julia',
  //     score: [10, 10, 10, 10, 60],
  //     total: 100,
  //   },
  //   {
  //     name: 'Sterzer Ivana',
  //     score: [0, 0, 25, 40, 25],
  //     total: 90,
  //   },
  //   {
  //     name: 'Ramos Soledad',
  //     score: [40, 10, 0, 25, 10],
  //     total: 85,
  //   },
  //   {
  //     name: 'Desabato Delfina',
  //     score: [80, 0, 0, 0, 0],
  //     total: 80,
  //   },
  //   {
  //     name: 'Paez Nancy',
  //     score: [80, 0, 0, 0, 0],
  //     total: 80,
  //   },
  //   {
  //     name: 'Ehrlich Cintia',
  //     score: [0, 10, 10, 60, 0],
  //     total: 80,
  //   },
  //   {
  //     name: 'Herman Nancy',
  //     score: [10, 10, 40, 10, 10],
  //     total: 80,
  //   },
  //   {
  //     name: 'Arrua Mari',
  //     score: [0, 0, 0, 10, 60],
  //     total: 70,
  //   },
  //   {
  //     name: 'Marquez Daiana',
  //     score: [0, 0, 40, 0, 25],
  //     total: 65,
  //   },
  //   {
  //     name: 'Minaglia Meli',
  //     score: [0, 0, 60, 0, 0],
  //     total: 60,
  //   },
  //   {
  //     name: 'Chaparro Lorena',
  //     score: [10, 0, 25, 10, 10],
  //     total: 55,
  //   },
  //   {
  //     name: 'Kramer Florencia',
  //     score: [10, 0, 40, 0, 0],
  //     total: 50,
  //   },
  //   {
  //     name: 'Ventancour Pitty',
  //     score: [0, 25, 25, 0, 0],
  //     total: 50,
  //   },
  //   {
  //     name: 'Rosales Noelia',
  //     score: [25, 25, 0, 0, 0],
  //     total: 50,
  //   },
  //   {
  //     name: 'Olmedo Ileana',
  //     score: [0, 0, 40, 0, 10],
  //     total: 50,
  //   },
  //   {
  //     name: 'Graf Angie',
  //     score: [10, 10, 10, 10, 10],
  //     total: 50,
  //   },
  //   {
  //     name: 'Darrechon Daniela',
  //     score: [10, 10, 25, 0, 0],
  //     total: 45,
  //   },
  //   {
  //     name: 'Kramer Dana',
  //     score: [0, 0, 10, 25, 10],
  //     total: 45,
  //   },
  //   {
  //     name: 'Duscht Teresa',
  //     score: [0, 0, 0, 0, 40],
  //     total: 40,
  //   },
  //   {
  //     name: 'Ross Maria Paz',
  //     score: [0, 40, 0, 0, 0],
  //     total: 40,
  //   },
  //   {
  //     name: 'Riffel Jesica',
  //     score: [0, 0, 0, 40, 0],
  //     total: 40,
  //   },
  //   {
  //     name: 'Arredondo Yanina',
  //     score: [0, 0, 0, 40, 0],
  //     total: 40,
  //   },
  //   {
  //     name: 'Vergara Mar',
  //     score: [0, 0, 0, 40, 0],
  //     total: 40,
  //   },
  //   {
  //     name: 'Muller Lorena',
  //     score: [0, 10, 10, 10, 10],
  //     total: 40,
  //   },
  //   {
  //     name: 'Facciano Carina',
  //     score: [0, 25, 0, 0, 0],
  //     total: 25,
  //   },
  //   {
  //     name: 'La Barba Debora',
  //     score: [0, 0, 0, 0, 25],
  //     total: 25,
  //   },
  //   {
  //     name: 'Gonzalez Dulcinea',
  //     score: [0, 0, 0, 0, 25],
  //     total: 25,
  //   },
  //   {
  //     name: 'Whilelm Delfina',
  //     score: [0, 0, 10, 10, 0],
  //     total: 20,
  //   },
  //   {
  //     name: 'Covacho Marcela',
  //     score: [10, 10, 0, 0, 0],
  //     total: 20,
  //   },
  //   {
  //     name: 'Reh Eleonora',
  //     score: [10, 10, 0, 0, 0],
  //     total: 20,
  //   },
  //   {
  //     name: 'Castañeda Claudia',
  //     score: [0, 0, 10, 10, 0],
  //     total: 20,
  //   },
  //   {
  //     name: 'Fontana Maria',
  //     score: [0, 0, 0, 10, 0],
  //     total: 10,
  //   },
  //   {
  //     name: 'Kramer Flavia',
  //     score: [0, 0, 0, 10, 0],
  //     total: 10,
  //   },
  //   {
  //     name: 'Gauna Dahiana',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //   },
  //   {
  //     name: 'Ostorero Sandra',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //   },
  //   {
  //     name: 'Martinez Ailen',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //   },

  //   // Añade más jugadores de la 'Categoria 2' según sea necesario
  // ],
  // 'Suma 14': [
  //   {
  //     name: 'Chaparro Yamil',
  //     score: [25, 40, 40, 80, 80],
  //     total: 265,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Huber Walter',
  //     score: [60, 10, 40, 100, 80],
  //     total: 250,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Thaut Gabriel',
  //     score: [100, 80, 25, 40, 0],
  //     total: 245,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Cortina Sandro',
  //     score: [25, 40, 40, 100, 40],
  //     total: 245,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Taulada Valentin',
  //     score: [40, 25, 80, 60, 25],
  //     total: 230,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Heffel Ariel',
  //     score: [60, 60, 10, 0, 100],
  //     total: 230,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Carrizo Daniel',
  //     score: [80, 40, 100, 0, 0],
  //     total: 220,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Navarro Benjamin',
  //     score: [80, 40, 100, 0, 0],
  //     total: 220,
  //     category: '7° OBS',
  //   },
  //   {
  //     name: 'Aguirre Demian',
  //     score: [60, 25, 0, 25, 100],
  //     total: 210,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Rodriguez Nicolas',
  //     score: [40, 25, 80, 60, 0],
  //     total: 205,
  //     category: '7° OBS',
  //   },
  //   {
  //     name: 'Herbel Rubito',
  //     score: [100, 80, 0, 0, 0],
  //     total: 180,
  //     category: '7° OBS',
  //   },
  //   {
  //     name: 'Bill Tati',
  //     score: [40, 60, 25, 25, 25],
  //     total: 175,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Goette Ariel',
  //     score: [25, 25, 60, 40, 25],
  //     total: 175,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Goette Juan',
  //     score: [25, 25, 60, 40, 25],
  //     total: 175,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Borgert Nicolas',
  //     score: [60, 60, 0, 0, 25],
  //     total: 145,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Gerlach Diego',
  //     score: [25, 40, 25, 25, 25],
  //     total: 140,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Fernandez Maximiliano',
  //     score: [25, 40, 25, 25, 25],
  //     total: 140,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Schmidt Martin',
  //     score: [40, 100, 0, 0, 0],
  //     total: 140,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Cardenal Valentin',
  //     score: [10, 0, 60, 60, 0],
  //     total: 130,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Erbes Gaston',
  //     score: [0, 0, 25, 40, 60],
  //     total: 125,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Kramer Karen',
  //     score: [0, 0, 60, 60, 0],
  //     total: 120,
  //   },
  //   {
  //     name: 'Martinez Maximiliano',
  //     score: [0, 0, 40, 40, 40],
  //     total: 120,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Schmidt Emanuel',
  //     score: [40, 0, 25, 25, 25],
  //     total: 115,
  //     category: '7° OBS',
  //   },
  //   {
  //     name: 'Martinez Rene',
  //     score: [0, 25, 25, 40, 25],
  //     total: 115,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Rios Tati',
  //     score: [10, 25, 0, 80, 0],
  //     total: 115,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Bill Juan Ignacio',
  //     score: [0, 0, 40, 0, 60],
  //     total: 100,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Arrua Nicolas',
  //     score: [10, 25, 40, 25, 0],
  //     total: 100,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Martinez Joel',
  //     score: [0, 100, 0, 0, 0],
  //     total: 100,
  //     category: '7° OBS',
  //   },
  //   {
  //     name: 'Diaz Silvestre',
  //     score: [10, 40, 10, 10, 25],
  //     total: 95,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Tiraboschi Joel',
  //     score: [10, 10, 10, 25, 40],
  //     total: 95,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Borgetto Maximiliano',
  //     score: [25, 25, 0, 0, 40],
  //     total: 90,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Ibarra Jose',
  //     score: [0, 60, 25, 0, 0],
  //     total: 85,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Borgetto Lucas',
  //     score: [25, 25, 10, 10, 10],
  //     total: 80,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Lezcano Gonzalo',
  //     score: [0, 0, 0, 0, 80],
  //     total: 80,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Senger Martin',
  //     score: [0, 25, 40, 10, 0],
  //     total: 75,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Tarabini Alan',
  //     score: [25, 10, 10, 10, 10],
  //     total: 65,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Pfeiffer Cristian',
  //     score: [0, 0, 25, 10, 25],
  //     total: 60,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Dietz Maximiliano',
  //     score: [10, 40, 0, 0, 10],
  //     total: 60,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Erhardt Leonardo',
  //     score: [0, 25, 25, 10, 0],
  //     total: 60,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Herman Carlos',
  //     score: [0, 0, 0, 0, 60],
  //     total: 60,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Herman Agustin',
  //     score: [0, 0, 0, 0, 60],
  //     total: 60,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Alvarez Josefina',
  //     score: [0, 10, 25, 10, 10],
  //     total: 55,
  //     category: '5°',
  //   },
  //   {
  //     name: 'Rodriguez Mauro',
  //     score: [10, 10, 0, 25, 10],
  //     total: 55,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Carrizo Enzo',
  //     score: [25, 0, 0, 25, 0],
  //     total: 50,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Ramos Soledad',
  //     score: [0, 0, 0, 25, 25],
  //     total: 50,
  //   },
  //   {
  //     name: 'Mayer Cristian',
  //     score: [0, 0, 0, 25, 25],
  //     total: 50,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Widmer Facundo',
  //     score: [0, 0, 10, 0, 40],
  //     total: 50,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Neif Facundo',
  //     score: [25, 0, 0, 25, 0],
  //     total: 50,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Acevedo Jose',
  //     score: [25, 10, 0, 10, 0],
  //     total: 45,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Cordoba Ivan',
  //     score: [0, 10, 0, 25, 10],
  //     total: 45,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Cordoba Nelson',
  //     score: [10, 0, 0, 25, 10],
  //     total: 45,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Todoni Brian',
  //     score: [0, 25, 10, 0, 10],
  //     total: 45,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Libralato Diego',
  //     score: [0, 0, 10, 10, 25],
  //     total: 45,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Flocco Ariel',
  //     score: [0, 0, 10, 10, 25],
  //     total: 45,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Tablada Gustavo',
  //     score: [0, 10, 10, 10, 10],
  //     total: 40,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Figueroa Facundo',
  //     score: [0, 0, 40, 0, 0],
  //     total: 40,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Gentina Matias',
  //     score: [0, 0, 0, 0, 40],
  //     total: 40,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Mingiaca Facundo',
  //     score: [40, 0, 0, 0, 0],
  //     total: 40,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Stier Cristian',
  //     score: [40, 0, 0, 0, 0],
  //     total: 40,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Lopez Marcos',
  //     score: [40, 0, 0, 0, 0],
  //     total: 40,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Belluzo Gaston',
  //     score: [0, 0, 0, 40, 0],
  //     total: 40,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Monzon Monchi',
  //     score: [0, 0, 0, 40, 0],
  //     total: 40,
  //     category: '7°',
  //   },
  //   {
  //     name: 'More Ulises',
  //     score: [25, 10, 0, 0, 0],
  //     total: 35,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Genovesio Lucas',
  //     score: [0, 25, 0, 0, 10],
  //     total: 35,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Genovesio Gabriel',
  //     score: [25, 0, 0, 10, 0],
  //     total: 35,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Gross Tuni',
  //     score: [10, 25, 0, 0, 0],
  //     total: 35,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Reula Marcos',
  //     score: [10, 25, 0, 0, 0],
  //     total: 35,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Moya Oscar',
  //     score: [0, 0, 0, 25, 10],
  //     total: 35,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Martinez Lautaro',
  //     score: [0, 0, 0, 10, 25],
  //     total: 35,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Algañaraz Cristian',
  //     score: [0, 0, 10, 10, 10],
  //     total: 30,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Beron Mario',
  //     score: [0, 10, 10, 10, 0],
  //     total: 30,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Trossero Alejo',
  //     score: [25, 0, 0, 0, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Cabello Yanina',
  //     score: [0, 0, 0, 0, 25],
  //     total: 25,
  //   },
  //   {
  //     name: 'Barquin Ulises',
  //     score: [25, 0, 0, 0, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Chiara Andres',
  //     score: [0, 0, 25, 0, 0],
  //     total: 25,
  //     category: '6°',
  //   },
  //   {
  //     name: 'Gauna Dahiana',
  //     score: [0, 0, 25, 0, 0],
  //     total: 25,
  //   },
  //   {
  //     name: 'Borgetto Lautaro',
  //     score: [0, 0, 25, 0, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Abrego Yamil',
  //     score: [0, 0, 25, 0, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Maitenon Jose',
  //     score: [0, 0, 25, 0, 0],
  //     total: 25,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Barquin Barbara',
  //     score: [0, 0, 0, 25, 0],
  //     total: 25,
  //   },
  //   {
  //     name: 'Eichman Mauro',
  //     score: [10, 0, 0, 0, 10],
  //     total: 20,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Seip Juan',
  //     score: [0, 10, 10, 0, 0],
  //     total: 20,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Viola Jose',
  //     score: [0, 10, 10, 0, 0],
  //     total: 20,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Moreira Valentin',
  //     score: [10, 0, 0, 10, 0],
  //     total: 20,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Alud Nelson',
  //     score: [10, 0, 0, 10, 0],
  //     total: 20,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Zabala Tochi',
  //     score: [0, 0, 10, 10, 0],
  //     total: 20,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Garcia Ale',
  //     score: [10, 0, 0, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Martinez Diego',
  //     score: [10, 0, 0, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Mingiaca Mercedes',
  //     score: [10, 0, 0, 0, 0],
  //     total: 10,
  //   },
  //   {
  //     name: 'Esquivel Monica',
  //     score: [0, 10, 0, 0, 0],
  //     total: 10,
  //   },
  //   {
  //     name: 'Carrizo Tata',
  //     score: [0, 10, 0, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Bill Gaston',
  //     score: [0, 10, 0, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Cortina Daiana',
  //     score: [0, 10, 0, 0, 0],
  //     total: 10,
  //   },
  //   {
  //     name: 'Algarañaz Matias',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Seip Jose',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Schmidt Brian',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Schmidt Kevin',
  //     score: [0, 0, 10, 0, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Albornoz Sebastian',
  //     score: [0, 0, 0, 10, 0],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Diaz Franco',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Darrechon Francisco',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Clementin Flavia',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //   },
  //   {
  //     name: 'Balbi Lucas',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Funes Gonzalo',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Santa Cruz Miguel',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Heft Benjamin',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '7°',
  //   },
  //   {
  //     name: 'Fucks Agustin',
  //     score: [0, 0, 0, 0, 10],
  //     total: 10,
  //     category: '7°',
  //   },
  // ],
};

export const circuitFeatures = [
  'Múltiples fechas y categorías.',
  'Interesantes premios y competitividad.',
  'Máster final.',
];

export const paddleClassesFeatures = [
  'Adaptamos las clases según tu nivel y objetivos.',
  'Unite a nuestras clases grupales. Grupos reducidos.',
  'No te preocupes por traer tu propia paleta. Proporcionamos todo el equipo necesario.',
];

export const buffetFeatures = [
  'Bebidas frías',
  'Café y agua caliente',
  'Hamburguesas, pizzas y sandwiches',
  'Golosinas y snacks',
];

export const clubFeatures = [
  {
    id: 'feature-1',
    imgUrl: '/cesped.webp',
    title: 'Cancha de césped',
  },
  {
    id: 'feature-2',
    imgUrl: '/cemento.webp',
    title: 'Cancha de cemento',
  },
  {
    id: 'feature-3',
    imgUrl: '/buffet.webp',
    title: 'Servicio de buffet',
  },
  {
    id: 'feature-4',
    imgUrl: '/terraza.webp',
    title: 'Terraza y vestuarios',
  },
];

export const marqueeImages = [
  { imgUrl: '/cesped.webp', alt: 'cancha de cesped' },
  { imgUrl: '/cemento.webp', alt: 'cancha de cemento' },
  { imgUrl: '/clases2.webp', alt: 'clases de padel' },
  { imgUrl: '/terraza.webp', alt: 'terraza' },
];
